import type { CatalogView } from "@/types/catalog";

const IMG = "/images/catalogo";

/**
 * MOCK TEMPORÁRIO DE CATÁLOGOS E PRODUTOS
 *
 * ATENÇÃO: Este arquivo é uma camada de dados temporária (mock local)
 * para viabilizar testes da renderização dinâmica antes da integração com o Supabase.
 * NÃO deve ser utilizado como fonte de dados em produção.
 */
export const TEMPORARY_CATALOG_MOCKS: CatalogView[] = [
  {
    id: "catalog-modulus-default",
    slug: "modulus",
    title: "Catálogo",
    eyebrow: "Objetos funcionais · impressão 3D",
    heroStrongText: "Projetados para o uso real.",
    heroCopy: "Uma seleção de objetos úteis, duráveis e produzidos sob demanda.",
    manifestoLabel: "Nosso princípio",
    manifestoTitle: "Menos descartável.\nMais essencial.",
    manifestoFormula: "E = σ / ε",
    manifestoDescription: "Módulo de elasticidade: E igual a sigma sobre epsilon",
    products: [
      {
        id: "prod-001",
        index: "MOD—001",
        name: "Luminária Shoji",
        category: "Iluminação",
        format: "Unitário",
        detail: "Iluminação · Impresso sob demanda",
        description:
          "Luz difusa em uma cúpula canelada de presença calma, feita para mesas laterais, cabeceiras e cantos de leitura.",
        photo: `${IMG}/mod-001-luminaria-shoji.webp`,
        photoAlt: "Luminária Shoji acesa com cúpula retangular canelada e base escura",
        price: null,
        displayOrder: 1,
      },
      {
        id: "prod-002",
        index: "MOD—002",
        name: "Luminária Nimbo",
        category: "Iluminação",
        format: "Unitário",
        detail: "Iluminação · Impresso sob demanda",
        description:
          "Volumes macios e luz acolhedora em uma peça escultórica, com base compacta e cúpula translúcida.",
        photo: `${IMG}/mod-002-luminaria-nimbo.webp`,
        photoAlt: "Luminária Nimbo acesa com cúpula branca de volumes arredondados e base azul",
        price: null,
        displayOrder: 2,
      },
      {
        id: "prod-003",
        index: "MOD—003",
        name: "Suporte Arco",
        category: "Organização",
        format: "Unitário",
        detail: "Organização · Impresso sob demanda",
        description:
          "Uma estrutura escultórica que mantém o fone elevado, organizado e protegido entre um uso e outro.",
        photo: `${IMG}/mod-003-suporte-arco.webp`,
        photoAlt: "Suporte Arco azul-marinho vazio, fotografado em estúdio",
        price: null,
        displayOrder: 3,
      },
      {
        id: "prod-004",
        index: "MOD—004",
        name: "Descansos Trama",
        category: "Casa",
        format: "Conjunto",
        detail: "Casa · Impresso sob demanda",
        description:
          "Conjunto de seis descansos com superfície vazada e estojo compacto para guardar tudo após o uso.",
        photo: `${IMG}/mod-004-descansos-trama.webp`,
        photoAlt: "Conjunto colorido de descansos de copo circulares com trama vazada e estojo",
        price: null,
        displayOrder: 4,
      },
      {
        id: "prod-005",
        index: "MOD—005",
        name: "Monstera Magnética",
        category: "Casa",
        format: "Conjunto",
        detail: "Casa · Impresso sob demanda",
        description:
          "Folhas magnéticas que viram descansos de copo e retornam à base como uma pequena escultura botânica.",
        photo: `${IMG}/mod-005-monstera-magnetica.webp`,
        photoAlt: "Folhas de Monstera magnéticas em base canelada lilás",
        price: null,
        displayOrder: 5,
      },
      {
        id: "prod-006",
        index: "MOD—006",
        name: "Módulo Entrada",
        category: "Organização",
        format: "Unitário",
        detail: "Organização · Impresso sob demanda",
        description: "Painel modular para reunir carteira, chaves e pequenos objetos essenciais logo na entrada.",
        photo: `${IMG}/mod-006-modulo-entrada.webp`,
        photoAlt: "Organizador modular de parede com carteira, chave e ramos secos",
        photoSecondary: `${IMG}/mod-006-modulo-entrada-vazio.webp`,
        photoSecondaryAlt: "Organizador modular de parede completamente vazio",
        photoNote: "Passe para ver vazio",
        price: null,
        displayOrder: 6,
      },
      {
        id: "prod-007",
        index: "MOD—007",
        name: "Luminária Órbita",
        category: "Iluminação",
        format: "Unitário",
        detail: "Iluminação · Impresso sob demanda",
        description:
          "Cúpula tramada e volumes concêntricos transformam a luz em uma presença suave, elevada por três pés esbeltos.",
        photo: `${IMG}/mod-007-luminaria-orbita.webp`,
        photoAlt: "Luminária Órbita acesa com cúpula branca ondulada sobre três pés",
        price: null,
        displayOrder: 7,
      },
      {
        id: "prod-008",
        index: "MOD—008",
        name: "Luminária Dobra",
        category: "Iluminação",
        format: "Unitário",
        detail: "Iluminação · Impresso sob demanda",
        description: "Uma única linha curva sustenta a luz e forma base, coluna e braço em um gesto mínimo e contínuo.",
        photo: `${IMG}/mod-008-luminaria-dobra.webp`,
        photoAlt: "Luminária Dobra acesa com estrutura contínua bege e pequena cúpula",
        price: null,
        displayOrder: 8,
      },
      {
        id: "prod-009",
        index: "MOD—009",
        name: "Vaso Dueto",
        category: "Decoração",
        format: "Unitário",
        detail: "Decoração · Impresso sob demanda",
        description:
          "Textura mineral e aletas verticais se encontram em um vaso de duas partes, pensado para destacar folhagens compactas.",
        photo: `${IMG}/mod-009-vaso-dueto.webp`,
        photoAlt: "Vaso Dueto com base clara texturizada, aro caramelo canelado e planta natural",
        price: null,
        displayOrder: 9,
      },
      {
        id: "prod-010",
        index: "MOD—010",
        name: "Calendário Perpétuo",
        category: "Organização",
        format: "Unitário",
        detail: "Organização · Impresso sob demanda",
        description: "Calendário tátil e reutilizável com marcadores móveis para acompanhar qualquer mês, ano após ano.",
        photo: `${IMG}/mod-010-calendario-perpetuo.webp`,
        photoAlt: "Calendário perpétuo azul-marinho com marcadores de dias, datas e meses",
        price: null,
        displayOrder: 10,
      },
      {
        id: "prod-011",
        index: "MOD—011",
        name: "Incensário Seixo",
        category: "Casa",
        format: "Unitário",
        detail: "Casa · Impresso sob demanda",
        description: "Uma forma baixa inspirada em pedra de rio, com cavidade ampla para receber as cinzas com discrição.",
        photo: `${IMG}/mod-011-incensario-seixo.webp`,
        photoAlt: "Incensário Seixo claro com textura mineral e uma vareta de incenso",
        price: null,
        displayOrder: 11,
      },
      {
        id: "prod-012",
        index: "MOD—012",
        name: "Incensário Pêndulo",
        category: "Casa",
        format: "Unitário",
        detail: "Casa · Impresso sob demanda",
        description:
          "A vareta fica suspensa e as cinzas caem em uma bandeja removível — um ritual simples em uma moldura precisa.",
        photo: `${IMG}/mod-012-incensario-pendulo.webp`,
        photoAlt: "Incensário Pêndulo azul-marinho com vareta suspensa e bandeja laranja",
        price: null,
        displayOrder: 12,
      },
      {
        id: "prod-013",
        index: "MOD—013",
        name: "Suporte Onda",
        category: "Organização",
        format: "Unitário",
        detail: "Organização · Impresso sob demanda",
        description:
          "Curvas contínuas mantêm o notebook na vertical, liberando espaço na mesa e protegendo o equipamento entre um uso e outro.",
        photo: `${IMG}/mod-013-suporte-onda.webp`,
        photoAlt: "Suporte Onda azul-marinho para notebook com cinco curvas verticais arredondadas",
        price: null,
        displayOrder: 13,
      },
      {
        id: "prod-014",
        index: "MOD—014",
        name: "Bandeja Campo",
        category: "Organização",
        format: "Unitário",
        detail: "Organização · Impresso sob demanda",
        description: "Três áreas de tamanhos diferentes organizam os pequenos essenciais do dia a dia em uma única peça compacta.",
        photo: `${IMG}/mod-014-bandeja-campo.webp`,
        photoAlt: "Bandeja Campo azul-marinho com três compartimentos de formas arredondadas",
        price: null,
        displayOrder: 14,
      },
      {
        id: "prod-015",
        index: "MOD—015",
        name: "Bandeja Módulo",
        category: "Organização",
        format: "Unitário",
        detail: "Organização · Impresso sob demanda",
        description:
          "Um compartimento amplo e dois nichos menores criam um lugar preciso para chaves, moedas, fones e objetos pessoais.",
        photo: `${IMG}/mod-015-bandeja-modulo.webp`,
        photoAlt: "Bandeja Módulo laranja com chave, moedas e estojo branco organizados em três espaços",
        price: null,
        displayOrder: 15,
      },
      {
        id: "prod-016",
        index: "MOD—016",
        name: "Porta-Copos Vitrola",
        category: "Casa",
        format: "Conjunto",
        detail: "Casa · Impresso sob demanda",
        description:
          "Uma mini vitrola giratória guarda quatro descansos em forma de vinil e transforma a mesa em uma pequena cena musical.",
        photo: `${IMG}/mod-016-porta-copos-vitrola.webp`,
        photoAlt: "Porta-Copos Vitrola azul-marinho com quatro descansos de copo em formato de discos de vinil",
        price: null,
        displayOrder: 16,
      },
    ],
  },
  {
    id: "catalog-maker-home",
    slug: "maker-home",
    title: "Maker Home",
    eyebrow: "Edição Especial · Organização & Casa",
    heroStrongText: "Ambientes com identidade e precisão.",
    heroCopy: "Objetos funcionais selecionados para espaços criativos e lares modernos.",
    manifestoLabel: "Design & Função",
    manifestoTitle: "Estética funcional.\nProduzida sob demanda.",
    manifestoFormula: "E = σ / ε",
    manifestoDescription: "Módulo de elasticidade: E igual a sigma sobre epsilon",
    products: [
      {
        id: "prod-001",
        index: "MOD—001",
        name: "Luminária Shoji",
        category: "Iluminação",
        format: "Unitário",
        detail: "Iluminação · Impresso sob demanda",
        description:
          "Luz difusa em uma cúpula canelada de presença calma, feita para mesas laterais, cabeceiras e cantos de leitura.",
        photo: `${IMG}/mod-001-luminaria-shoji.webp`,
        photoAlt: "Luminária Shoji acesa com cúpula retangular canelada e base escura",
        price: 249.9,
        displayOrder: 1,
      },
      {
        id: "prod-003",
        index: "MOD—003",
        name: "Suporte Arco",
        category: "Organização",
        format: "Unitário",
        detail: "Organização · Impresso sob demanda",
        description:
          "Uma estrutura escultórica que mantém o fone elevado, organizedo e protegido entre um uso e outro.",
        photo: `${IMG}/mod-003-suporte-arco.webp`,
        photoAlt: "Suporte Arco azul-marinho vazio, fotografado em estúdio",
        price: 139.0,
        displayOrder: 2,
      },
      {
        id: "prod-006",
        index: "MOD—006",
        name: "Módulo Entrada",
        category: "Organização",
        format: "Unitário",
        detail: "Organização · Impresso sob demanda",
        description: "Painel modular para reunir carteira, chaves e pequenos objetos essenciais logo na entrada.",
        photo: `${IMG}/mod-006-modulo-entrada.webp`,
        photoAlt: "Organizador modular de parede com carteira, chave e ramos secos",
        photoSecondary: `${IMG}/mod-006-modulo-entrada-vazio.webp`,
        photoSecondaryAlt: "Organizador modular de parede completamente vazio",
        photoNote: "Passe para ver vazio",
        price: 189.0,
        displayOrder: 3,
      },
    ],
  },
  {
    id: "catalog-deuses-gregos",
    slug: "deuses-gregos",
    title: "Deuses Gregos",
    eyebrow: "Coleção Mitológica · Impressão 3D",
    heroStrongText: "Esculturas inspiradas na antiguidade.",
    heroCopy: "Linha exclusiva de bustos, vasos e objetos decorativos clássicos.",
    manifestoLabel: "Mitologia & Arte",
    manifestoTitle: "Mitos clássicos.\nTecnologia contemporânea.",
    manifestoFormula: "Φ = 1.618",
    manifestoDescription: "Proporção áurea e harmonia visual",
    products: [
      {
        id: "prod-009",
        index: "MOD—009",
        name: "Vaso Dueto (Apolo)",
        category: "Decoração",
        format: "Unitário",
        detail: "Decoração · Impresso sob demanda",
        description: "Textura mineral e aletas verticais inspiradas nas colunas do Templo de Delfos.",
        photo: `${IMG}/mod-009-vaso-dueto.webp`,
        photoAlt: "Vaso Dueto com textura mineral clara",
        price: 199.0,
        displayOrder: 1,
      },
      {
        id: "prod-007",
        index: "MOD—007",
        name: "Luminária Órbita (Atena)",
        category: "Iluminação",
        format: "Unitário",
        detail: "Iluminação · Impresso sob demanda",
        description: "Cúpula tramada que evoca a sabedoria e iluminação serena dos templos clássicos.",
        photo: `${IMG}/mod-007-luminaria-orbita.webp`,
        photoAlt: "Luminária Órbita acesa",
        price: 320.0,
        displayOrder: 2,
      },
    ],
  },
];
